# Generated by Django 3.2 on 2021-04-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightingUsageRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('DeviceName', models.CharField(max_length=50)),
                ('OpenTime', models.TimeField()),
                ('CloseTime', models.TimeField()),
                ('Duration', models.IntegerField()),
                ('RecordTime', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
