# Generated by Django 3.2 on 2021-04-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_lightingusagerecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightingusagerecord',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
