# Generated by Django 3.2 on 2021-04-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_lightingusagerecord_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LightingUsageRecord',
            new_name='Lighting_Usage_Record',
        ),
    ]
