# Generated by Django 3.2 on 2021-04-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_lightingusagerecord_lighting_usage_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighting_usage_record',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
