# Generated by Django 3.2 on 2021-04-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_lighting_usage_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighting_usage_record',
            name='CloseTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lighting_usage_record',
            name='OpenTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lighting_usage_record',
            name='RecordTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
