# Generated by Django 3.2 on 2021-04-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210427_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighting_usage_record',
            name='RecordTime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
