# Generated by Django 3.2 on 2021-04-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_lighting_usage_record_recordtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lighting_Timer_Work_Queues',
            fields=[
                ('WorkNumber', models.AutoField(primary_key=True, serialize=False)),
                ('WorkContent', models.CharField(max_length=200)),
                ('DeviceStatus', models.BooleanField()),
                ('DeviceBrightness', models.IntegerField()),
                ('TimeRules', models.CharField(max_length=80)),
                ('CreateTime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
